// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SRVRecordParser
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("raw_record")]
        public string RawRecord { get; set; }

        [JsonProperty("parsed")]
        public Parsed Parsed { get; set; }

        [JsonProperty("service_info")]
        public ServiceInfo ServiceInfo { get; set; }

        [JsonProperty("interpretation")]
        public Interpretation Interpretation { get; set; }

        [JsonProperty("is_valid")]
        public bool IsValid { get; set; }
    }

    public partial class Interpretation
    {
        [JsonProperty("priority_explanation")]
        public string PriorityExplanation { get; set; }

        [JsonProperty("weight_explanation")]
        public string WeightExplanation { get; set; }

        [JsonProperty("target_explanation")]
        public string TargetExplanation { get; set; }
    }

    public partial class Parsed
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("service")]
        public string Service { get; set; }

        [JsonProperty("protocol")]
        public string Protocol { get; set; }

        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("ttl")]
        public long Ttl { get; set; }

        [JsonProperty("class")]
        public string Class { get; set; }

        [JsonProperty("priority")]
        public long Priority { get; set; }

        [JsonProperty("weight")]
        public long Weight { get; set; }

        [JsonProperty("port")]
        public long Port { get; set; }

        [JsonProperty("target")]
        public string Target { get; set; }
    }

    public partial class ServiceInfo
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("default_port")]
        public long DefaultPort { get; set; }
    }
}
